# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

target 'Triangle_swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Triangle_swift
  pod 'App-Notice'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GoogleMobileAds'

end
